const express = require('express');
const router = express.Router();
const controller = require('../controller/userController');
const { userAuthenticated } = require('../middleware/authentication');

router.get('/login', controller.getLogin);
router.post('/login', controller.loginUser);
router.get('/signup', controller.getSignup);
router.post('/register', controller.addUser);
router.post('/verify-otp', controller.verifyOtp);
router.post('/resend-otp', controller.resendOtp);
router.get('/home', controller.getHome);
router.get('/single-product/:id', controller.getSingleProduct);
router.get('/related-products/load-more', controller.loadMoreRelatedProducts);
router.get('/profile', userAuthenticated, controller.getUserProfile);
router.post('/profile/update', userAuthenticated, controller.updateUserProfile);
router.post('/profile/update-email', userAuthenticated, controller.updateEmail);
router.post('/profile/update-phone', userAuthenticated, controller.updatePhoneNumber);
router.get('/address', userAuthenticated, controller.getAddresses);
router.post('/address/add', userAuthenticated, controller.addAddress);
router.put('/address/edit/:id', userAuthenticated, controller.editAddress);
router.delete('/address/delete/:id', userAuthenticated, controller.deleteAddress);
router.post('/profile/change-password', userAuthenticated, controller.changePassword);
router.get('/cart', userAuthenticated, controller.getCart);
router.post('/cart/add', userAuthenticated, controller.addToCart);
router.delete('/cart/remove', userAuthenticated, controller.removeFromCart);
router.put('/cart/update', userAuthenticated, controller.updateQuantity);
router.get('/checkout', userAuthenticated, controller.checkoutPage);
router.post('/checkout/confirm-order', userAuthenticated, controller.confirmOrder);
router.post('/create-razorpay-order', userAuthenticated, controller.createRazorpayOrder);
router.post('/razorpay-confirm', userAuthenticated, controller.confirmRazorpayPayment);
router.get('/get-wallet-balance', userAuthenticated, controller.getWalletBalance);
router.post('/deduct-wallet-amount', userAuthenticated, controller.deductWalletAmount);
router.post('/checkout/apply-coupon', userAuthenticated, controller.applyCoupon);
router.get('/order-success', userAuthenticated, controller.getOrderSuccessPage);
router.get('/orders', userAuthenticated, controller.getUserOrders);
router.get('/order/:id', userAuthenticated, controller.getOrderDetails);
router.get('/order/invoice/:id', userAuthenticated, controller.downloadInvoice);
router.post('/orders/cancel/:id/:productId', userAuthenticated, controller.cancelProduct);
router.post('/orders/return/:id/:productId', userAuthenticated, controller.returnProduct);
router.get('/shop', controller.getShopPage);
router.get('/shop/load-more', controller.loadMoreProducts);
router.get('/wallet', userAuthenticated, controller.getWallet);
router.get('/forgot-password', controller.getForgotPassword);
router.post('/send-otp-password-reset', controller.sendOtpForPasswordReset);
router.post('/verify-otp-password-reset', controller.verifyOtpForPasswordReset);
router.post('/reset-password', controller.resetPassword);
router.post('/resend-otp-password-reset', controller.resendPasswordResetOtp);
router.get('/wishlist', userAuthenticated, controller.getWishlist);
router.post('/add-to-wishlist', userAuthenticated, controller.addToWishlist);
router.delete('/wishlist/remove/:productId', userAuthenticated, controller.deleteFromWishlist);
router.post('/logout', userAuthenticated, controller.logout);

// Reviews
router.post('/reviews/add', userAuthenticated, controller.postReview);
router.get('/reviews/load-more/:productId', controller.loadMoreReviews);

module.exports = router;
