const express = require('express');
const router = express.Router();
const controller = require('../controller/userController');
const { userAuthenticated } = require('../middleware/authentication');

router.get('/login', controller.getLogin);
router.post('/login', controller.loginUser);
router.get('/signup', controller.getSignup);
router.post('/register', controller.addUser);
router.post('/verify-otp', controller.verifyOtp);
router.post('/resend-otp', controller.resendOtp);
router.get('/home', controller.getHome);
router.get('/single-product/:id', controller.getSingleProduct);
router.get('/profile', userAuthenticated, controller.getUserProfile);
router.post('/profile/update', controller.updateUserProfile);
router.post('/profile/update-email', controller.updateEmail);
router.post('/profile/update-phone', controller.updatePhoneNumber);
router.get('/address', userAuthenticated, controller.getAddresses);
router.post('/address/add', controller.addAddress);
router.put('/address/edit/:id', controller.editAddress);
router.delete('/address/delete/:id', controller.deleteAddress);
router.post('/profile/change-password', controller.changePassword);
router.get('/cart', userAuthenticated, controller.getCart);
router.post('/cart/add', controller.addToCart);
router.delete('/cart/remove', controller.removeFromCart);
router.put('/cart/update', controller.updateQuantity); 
router.get('/checkout', userAuthenticated, controller.checkoutPage);
router.post('/checkout/confirm-order', controller.confirmOrder);
router.post('/create-razorpay-order', controller.createRazorpayOrder);
router.post('/razorpay-confirm', controller.confirmRazorpayPayment);
router.get('/get-wallet-balance', controller.getWalletBalance);
router.post('/deduct-wallet-amount', controller.deductWalletAmount);
router.post('/checkout/apply-coupon', controller.applyCoupon);
router.get('/order-success', userAuthenticated, controller.getOrderSuccessPage);
router.get('/orders', userAuthenticated, controller.getUserOrders);
router.get('/order/:id', userAuthenticated, controller.getOrderDetails);
router.get('/order/invoice/:id', userAuthenticated,controller.downloadInvoice);
router.post('/orders/cancel/:id/:productId',  userAuthenticated, controller.cancelProduct);
router.post('/orders/return/:id/:productId', controller.returnProduct);
router.get('/shop',controller.getShopPage);
router.get('/wallet', userAuthenticated,controller.getWallet);
router.post('/send-otp-password-reset', controller.sendOtpForPasswordReset);
router.post('/verify-otp-password-reset', controller.verifyOtpForPasswordReset);
router.post('/reset-password', controller.resetPassword);
router.post('/resend-otp-password-reset', controller.resendPasswordResetOtp); 
router.get('/wishlist',userAuthenticated, controller.getWishlist);
router.post('/add-to-wishlist', controller.addToWishlist);
router.delete('/wishlist/remove/:productId', controller.deleteFromWishlist);
router.post('/logout', controller.logout);

module.exports = router;
